# Site settings
locale: "en-US"
title: Zhengwei Luo
email: zhengweiluo@alumni.stanford.edu
description: >-
  Zhengwei Luo's personal webpage.
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
timezone: America/Los_Angeles

atom_feed:
  hide: true

include:
  - _pages

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

author:
  name   : "Zhengwei Luo"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Builder; Leader in Growth Strategy & Business Operations"
  location : "Seattle, WA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:zhengweiluo@alumni.stanford.edu"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/zhengweiluo/"

footer:
  links: []

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
